### ISSUE TITLE
Maps not being deleted

### ISSUE THREAD

**Issue by EsDeKa** [JarnoVgr/Mr.Green-MTA-Resources#82] opened 2016-01-10 12:49 UTC
According to moshpit deleted maps stay on the server even though they show deleted in the log.

I'll look into this after my exams.

**Comment by AfuSensi** [comment] 2016-01-22 19:38
Fixed in my next commit

**Comment by JohnCena54** [comment] 2016-01-31 15:15
Cena approves this!

**Comment by AfuSensi** [comment] 2016-02-03 00:12
The problem is github keeps reuploading the deleted maps, so they actually do get deleted.
SDK is going to talk to ywa about it.

**Comment by EsDeKa** [comment] 2016-02-03 00:22
Apparently there seem to be maps in the original git repo folder /Race(mix)/repository/resources/[maps] which shouldn't be happening because there are none on git itself

An issue with the syncer @JarnoVgr ?

**Comment by EsDeKa** [comment] 2016-02-04 16:19
We solved the mystery
Should be fixed now @JohnCena54, there might be some issues with maps that didnt get deleted properly but we can delete those manually

**Comment by AleksCore** [comment] 2016-08-10 22:55
Fixed I guess.

**Closed by AleksCore** 2016-08-10 22:55 UTC
Labels: bug, fixed
